class Variable{
public static void main(String a[]){
String riverName="kaveri";
int noOfStatesItRuns=2;
int waterLevelInMeter=1341;
String templeName="Tirupathi";
int noOfVisiters=50000;
String laptopShowroom="HP world";
int ratings=4;
int heroKyotoCost=5899;
boolean isAvailableToBuy=true;
String zooName="Mysore Zoo";
boolean isOpen=false;
String trainName="Kaveri Express";
int trainNO=16222;
String countryName="Germany";
int populationInCrores=8;
String songName="Raabatha";
String singerName="Arjith Singh";
int noOfMinutes=5;
String clothesName="Trousers";
int clothesCost=2999;
String shoesBrandName="Adidas";
int shoesCost=2611;
boolean isAvailableForDelivary=true;
String spectaclesBrand="Ray Ban";
int spectaclesCost=5190;
String planetName="Vinus";
int position=2;
String aquaticAnimalName="Fighter Fish";
int lifeSpan=4;
String cricketPlayer="M S Dhoni";
int noOfScore=115;
int aurvedicRecipeCost=1550;
boolean isAvailableForPurchase=true;
String cameraName="Nikon";
int pixel=5000;
String soapName="Dove";
int costOfPerSoap=60;
String icecream="Chocolate Icecream";
int noOfRequirements=500;
String umbrellaBrand="Camlin";
int umbrellaCost=400;
String roadName="Nehru Road";
int noOfVehicals=5000;
System.out.println(riverName);
System.out.println(noOfStatesItRuns); 
System.out.println(waterLevelInMeter);
System.out.println(templeName);
System.out.println(noOfVisiters);
System.out.println(laptopShowroom);
System.out.println(ratings);
System.out.println(heroKyotoCost);
System.out.println(isAvailableToBuy);
System.out.println(zooName);
System.out.println(isOpen);
System.out.println(trainName);
System.out.println(trainNO);
System.out.println(countryName);
System.out.println(populationInCrores);
System.out.println(songName);
System.out.println(singerName);
System.out.println(noOfMinutes);
System.out.println(clothesName);
System.out.println(clothesCost);
System.out.println(shoesBrandName);
System.out.println(shoesCost);
System.out.println(isAvailableForDelivary);
System.out.println(spectaclesBrand);
System.out.println(spectaclesCost);
System.out.println(planetName);
System.out.println(position);
System.out.println(aquaticAnimalName);
System.out.println(lifeSpan);
System.out.println(cricketPlayer);
System.out.println(noOfScore);
System.out.println(aurvedicRecipeCost);
System.out.println(isAvailableForPurchase);
System.out.println(cameraName);
System.out.println(pixel);
System.out.println(soapName);
System.out.println(costOfPerSoap);
System.out.println(icecream);
System.out.println(noOfRequirements);
System.out.println(umbrellaBrand);
System.out.println(umbrellaCost);
System.out.println(roadName);
System.out.println(noOfVehicals);

}


}